### ISSUE TITLE
复现论文表格第十二行的结果需要的参数设置

### ISSUE THREAD

**Issue by Janeey99** [thu-spmi/damd-multiwoz#12]
您好，非常感谢您出色的工作！
我想复现论文中表格第12行的结果。Inform:76.3, Success:60.4, Bleu:16.6,Combined Score: 85.0。
是不是仅需要把config.py里的self.bspn_mode 更改为'bspn'就好了呢？还需要其他更改吗？比如self.aspn_decode_mode='gready'？
期待您的回复。

**Comment by 594zyc** [comment]
> 需要把config.py里的self.bspn_mode 更改为'bspn'

对

> 还需要其他更改吗？比如self.aspn_decode_mode='gready'？

不用，其他设定直接用config.py里的就可以（self.aspn_decode_mode = 'greedy' already holds）
