### ISSUE TITLE
Where is `db/value_set.json` from?

### ISSUE THREAD

**Issue by failable** [thu-spmi/damd-multiwoz#7]
Hi, can you tell me where is `db/value_set.json` from and what is it? The original data set seems does not contain it. Thanks!

**Comment by 594zyc** [comment]
It should be created after running the preprocessing.

**Comment by failable** [comment]
I mean how it is created and what is it. It is read [here](https://gitlab.com/ucdavisnlp/damd-multiwoz/blob/master/preprocess.py#L18). But I don't seem to find any code that created it.

**Comment by 594zyc** [comment]
It is the collection of all possible values for each slot in the dataset. It is originated from [here](https://github.com/ConvLab/ConvLab/blob/a04582a77537c1a706fbf64715baa9ad0be1301a/data/value_set.json) in the Convlab repository.

**Comment by failable** [comment]
Thanks for the clarification.
